config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show] do
    resources :wikis, shallow: true do
      resources :collaborators
    end
  end
  
  resources :wikis, only: [:index]
  resources :charges, only: [:new, :create]
  delete '/downgrade', to: 'charges#downgrade'
  
  authenticated do
    root to: "users#show", as: :authenticated
  end
  
  root to: 'welcome#index'
  
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_many :collaborators
  has_many :wikis
  has_many :collaborations, through: :collaborators, source: :wiki_id
  
  after_initialize :set_role
  
  def set_role
    self.role ||= 'standard'
  end
  
  def admin?
    role == 'admin'
  end
  
  def premium?
    role == 'premium'
  end
  
  def standard?
    role == 'standard'
  end
  
  def make_wikis_public
    wikis.each do |wiki|
      if wiki.private == true
        wiki.update_attributes(private: false)
      end
    end
  end
  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  
  belongs_to :user
  
  has_many :collaborators
  has_many :users, through: :collaborators
  
  scope :visible_to, -> (user) { user ? all : where(private: false) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include Pundit
  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
 
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Membership - #{current_user.email}",
      amount: 15_00
      }
  end
  
  def create
    @user = current_user
    # Creates a Stripe Customer object, for associating with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
  
    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: 15_00,
      description: "Blocipedia Membership - #{current_user.email}",
      currency: 'usd'
    )
    
    @user.update(role: 'premium')
    flash[:success] = "Thanks for your subscription, #{current_user.name}!"
    redirect_to root_path
  
    # Stripe will send back CardErrors, with friendly messages when something goes wrong.
    # This 'rescue block' catches and displays those errors.
    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  
  end
  
  def downgrade
    @user = current_user
    @user.update(role: 'standard')
    @user.make_wikis_public
    redirect_to root_path
  end
  
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  
  def new
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new
    @users = (User.all - [current_user])
  end
  
  def create
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = @wiki.collaborators.create(collab_params)
    if @collaborator.save
      flash[:notice] = "Collaborators have been saved"
      redirect_to root_path
    else
      flash[:error] = "There was an error saving your collaborators. Please try again"
      render :new
    end
  end
  
  def destroy
    
  end
  
  private
  
  def collab_params
    params.require(:collaborator).permit(:user_id, :wiki_id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  
  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end
  
  def show
    @user = current_user
    @wikis = @user.wikis
    @collaborations = get_collaborated_wikis    
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :role)
  end
  
  def get_collaborated_wikis
    @all_wikis = Wiki.all
    @user = current_user
    @collaborated_wikis = []
    @all_wikis.each do |wiki|
      if wiki.users.include?(@user)
        @collaborated_wikis << wiki
      end
    end
    @collaborated_wikis
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.users
    authorize @wiki
  end

  def new
    @user = User.find(params[:user_id])
    @wiki = Wiki.new
    authorize @wiki
  end

  def edit
    @user = current_user
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def create
    @user = current_user
    @wiki = @user.wikis.create(wiki_params)
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was saved"
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the Wiki. Please try again"
      render :new
    end
  end
  
  def update
    @user = current_user
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes(params.require(:wiki).permit(:title, :body, :user_id, :private, :collaborator_id, :user_ids => []))
      redirect_to @wiki
    else
      flash[:error] = "Error saving wiki. Please try again"
      render :edit
    end
  end
  
  def destroy
    @user = current_user
    @wiki = Wiki.find(params[:id])
    title = @wiki.title
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully"
      redirect_to root_path
    else
      flash[:error] = "There was an error deleting the wiki"
      render :show
    end
  end
  
  private
  
  def wiki_params
    params.require(:wiki).permit(:title, :body, :user_id, :private, :collaborator_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
  
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    
    <%= form_tag charges_path do %>
      <h4>Upgrade to Premium</h4>
      <script 
        class='stripe-button' 
        src="https://checkout.stripe.com/checkout.js" 
        data-key="<%= @stripe_btn_data[:key] %>" 
        data-amount=<%= @stripe_btn_data[:amount] %> 
        data-name="Blocipedia"
        data-description="One Year Membership"
        data-email="<%= @stripe_btn_data[:email] %>" >
      </script>
    <% end %>
    
  </div>
</div>

app/views/collaborators/new.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    
    <h4 class="center-align">Add Collaborators to <%= @wiki.title %></h4><br />
    
    <%= form_for @wiki do |f| %>
      <div class="field">
        <%= f.label :user_ids, "Collaborators" %>
        <%= f.collection_select :user_ids, @users, :id, :name,{ include_blank: true }, { multiple: true, class: "browser-default" } %>
      </div><br />
    
      <div class="field center-align">
        <%= f.submit "Save", class: 'btn grey darken-1' %>
      </div>
    
    <% end %>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <!--Import materialize.css-->
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  </head>

  <body>
    
    <div class="container">
      <nav>
        <div class="nav-wrapper light-blue">
          &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Blocipedia", root_path, class: 'center-align' %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if current_user %>
              <li><%= link_to "Browse Wiki's", wikis_path %></li>
              <li><%= link_to "My Wiki's", root_path %></li>
              <li><%= link_to "User Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </nav><br />  
      
      <% if flash[:notice] %>
        <script>
          Materialize.toast('<%= flash[:notice] %>', 2000, 'green');
        </script>
      <% elsif flash[:error] %>
        <script>
          Materialize.toast('<%= flash[:error] %>', 3000, 'red');
        </script>
      <% elsif flash[:alert] %>
        <script>
          Materialize.toast('<%= flash[:alert] %>', 3000, 'orange');
        </script>
      <% end %>
    
      <%= yield %>
      
    </div>    
  </body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    
    <br /><h4 class="center-align">My wikis</h4><br />
    
    <table class="bordered hoverable">
      <tbody>
        <% @wikis.each do |wiki| %>
          <tr>
            <td><%= link_to wiki.title, wiki_path(wiki.id) %></td>
            <td class="right-align"><%= link_to "Edit", edit_wiki_path(wiki), class: 'black-text' %></td>
            <td class="center-align"><%= link_to "Delete", wiki, method: :delete, class: 'red-text', data: {confirm: 'Are you sure you want to delete this Wiki?'} %></td>
          </tr>
        <% end %>  
      </tbody>
    </table><br /><br />
    
    <% if @collaborations.present? %>
      <h4 class="center-align">Wikis I collaborate on</h4><br />
      <table class="bordered hoverable">
        <tbody>
          <% @collaborations.each do |wiki| %>
            <tr>
              <td><%= link_to wiki.title, wiki_path(wiki.id) %></td>
              <td class="right-align"><%= link_to "Edit", edit_wiki_path(wiki), class: 'black-text' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
            </tr>
          <% end %>  
        </tbody>
      </table><br /><br />
    <% end %>
    
    <div class="center-align">
      <%= link_to "New Wiki", new_user_wiki_path(@user, @wiki), class: 'btn grey darken-1' %>
    </div>
    
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  
  <div class="col s8 offset-s2 center-align">
    <br /><h4>Blocipedia: Social, Markdown Wikis</h4><br />
    <div class="card light-blue lighten-2 white-text"><br />
      <h5>Create and share Markdown Wikis</h5><br />
      <%= link_to "Sign Up", new_user_registration_path, class: 'waves-effect waves-light grey darken-1 btn' %><p></p><br />
    </div>
  </div>
  
</div>

<div class="row">
  
  <div class="col s4 offset-s2 center-align">
    <div class="card grey darken-1 white-text">
      <p>Create as many public<br />
      wikis as you want with our<br />
      Free Plan!</p>
    </div>
  </div>
  
  <div class="col s4 center-align">
    <div class="card grey darken-1 white-text">
      <p>Create private wikis<br />
      with a paid<br />
      Premium Plan!</p>
    </div>
  </div>
  
</div>

app/views/wikis/edit.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    
    <h4 class="center-align">Editing <%= markdown_to_html @wiki.title %></h4>
    
    <%= form_for [@wiki] do |f| %>
    
      <div class="field">
        <%= f.label :title, autofocus: true %>
        <%= f.text_field :title %>
      </div><br />
    
      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'materialize-textarea', id: 'textarea1' %>
      </div><br />
    
      <div class="field center-align">
        <%= f.submit "Save", class: 'btn grey darken-1' %>
      </div><br /><br />
    
    <% end %>  
  </div>
  
  <% if @user.role == 'premium' %>
    <div class="col s2"><br />
      <h6>Add collaborators?</h6><br />
      <%= link_to "Collaborators", new_wiki_collaborator_path(@wiki, @collaborator), class: 'btn grey darken-1' %>
    </div>
  <% end %>
  
</div>

app/views/wikis/index.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    
    <br /><h4 class="center-align">All Wiki's</h4><br />
    
    <table class="bordered hoverable">
      <tbody>
        <% @wikis.each do |wiki| %>
          <tr>
            <td><%= link_to wiki.title, wiki_path(wiki.id) %></td>
            <td class="right-align">Created by <%= wiki.user.name %></td>
          </tr>
        <% end %>  
      </tbody>
    </table><br /><br />

  </div>
</div>

app/views/wikis/new.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    
    <h4 class="center-align">New Wiki</h4>
    
    <%= form_for [@user, @user.wikis.build] do |f| %>
    
      <div class="field">
        <%= f.label :title, autofocus: true %>
        <%= f.text_field :title %>
      </div><br />
    
      <div class="input_field">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'materialize-textarea' %>
      </div><br />
    
      <% if current_user.role == 'admin' || current_user.role == 'premium' %>
        <div class="field">
          <%= f.check_box :private %>
          <%= f.label :private %>
        </div><br />
      <% end %>
      
      <div class="field center-align">
        <%= f.submit "Save", class: 'btn grey darken-1' %>
      </div>
    
    <% end %>
    
  </div>
</div>

app/views/wikis/show.html.erb
<div class="row">
  
  <div class="col s8 offset-s2">
    
    <h4 class="center-align"><%= markdown_to_html @wiki.title %></h4>
    
    <p class="center-align">Creator: <%= @wiki.user.name %></p><br />
    
    <p><%= markdown_to_html @wiki.body %></p><br /><br />
    
  </div>
  
  <div class="col s2 center-align"><br /><br />
    <% if policy(@wiki).edit? %>
      <%= link_to "Edit wiki", edit_wiki_path(@wiki), class: 'light-green btn' %><br /><br />
    <% end %>
    <% if policy(@wiki).destroy? %>
      <%= link_to "Delete wiki", wiki_path(@wiki), class: 'red btn', method: :delete, data: {confirm: 'Are you sure you want to delete this Wiki?'} %>
    <% end %><br /><br />
    <% if @collaborators.present? %>
      <h5>Collaborators</h5>
      <table class="bordered hoverable">
        <tbody>
          <% @collaborators.each do |user| %>
            <tr>
              <td class="center-align"><%= user.name %></td>
            </tr>
          <% end %>  
        </tbody>
      </table>
    <% end %>
  </div>
  
</div>